---
title: Jekyl Test Site
timezone: UTC
collections:
  cards:
    title: Cards
    output: true
    Field name:
    - Featured  image: 
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: toni@fairheadcreative.com
description: This is a test Jekyll site. Use it but don't abuse it.
baseurl: ''
url: http://testjekyllhead.com
twitter_username: 
github_username: tonigugic
permalink: "/:title/"
exclude:
- README.md
- Gemfile
- Gemfile.lock
- gruntfile.js
- package.json
- node_modules
- js/layout
- js/production.js
- vendor
- Rakefile
- Procfile
- config.ru
plugins:
- jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
